#DATA_PATH: 'input/dataset/Augmented_cv_10/*/*.mat'
DATA_PATH: 'input/dataset/whole_separated/*/*.mat'
INFO_FILE: 'input/dataset/whole_separated/info.xlsx'

TYPE: train #OPTIONS: train - for the split train, cv - for the crossvalidation
MODEL_CONFIGS: [unet_al, unet_tr_al, unet, unet_tr]
IMAGE_SIZE: [256, 256]
LOG_CONFIG: False
DISTRUBUTE_TRAIN: False
SEED: 2021
TESLA_PROGRESS: False