ACTIVATION: relu
PADDING: same
FILTERS: 64
NOISE_LEVEL: 0.35
PDROP: 0.3
K_INITIALIZER: 'he_normal'
CHANNELS: 3
POOL_SIZE: [2, 2]
N_DOWN_LAYERS: 4
N_UP_LAYERS: 4
MODEL_NAME: 'UNet_AL'
LOSS: 'binary_crossentropy'
AT_CONV_TYPE: 'none'
LR: !!float 5e-3
OPTIMIZER: Adam
METRIC: dice_coef
BATCH_SIZE: 32
EPOCHS: 500
FIT_VERBOSE: 1
SCHEDULER: exp_restart

WEIGHTS_PATH: models/UNet_AL_4down_4up_/UNet_AL_model.60-0.7425-0.010246_20220329-165505.h5
FINETUNE: True

